added GetProfileType Part extension method and ProfileType enum
Apibim-com/Tekla.Extensions pull request #10
Opened 2023-07-29 14:48 UTC by keepdream1ng

I added Part extension method GetProfileType() and ProfileType enum with a simplest converter. Enum still has string values in its attributes in case we will need to parse them.

2023-07-31 06:45 UTC, keepdream1ng commented
Link below to converters performance benchmark just in someone will need it later.
https://github.com/keepdream1ng/EnumToStringConverterBenchmark.git

2023-07-31 19:40 UTC, Blogbotana requested changes
Поправишь немного и можно мерджить

2023-07-31 19:40 UTC, Blogbotana commented on Tekla.Extension/Services/ProfileTypeEnumConverter.cs
> +namespace Tekla.Extension.Services;
А почему такой namespace?

2023-07-31 19:40 UTC, Blogbotana commented on Tekla.Extension/Services/ProfileTypeEnumConverter.cs
> +                return (ProfileType)(-1);
Тут я бы сделал Unknown в Enum добавил бы и тут возвращал бы

2023-08-01 13:22 UTC, keepdream1ng commented on Tekla.Extension/Services/ProfileTypeEnumConverter.cs
> +namespace Tekla.Extension.Services;
Это же не прямой функционал, а внутренний. Кому захочется применить - наверно смогут найти. Склоняюсь чтоб оставить так, но можно и поменять

2023-08-01 13:23 UTC, keepdream1ng commented on Tekla.Extension/Services/ProfileTypeEnumConverter.cs
> +                return (ProfileType)(-1);
Согласен.

2023-08-01 13:32 UTC, keepdream1ng commented
В новом коммите добавил Unknown в ProfileType
https://github.com/Blogbotana/Tekla.Extensions/blob/3bbc905aa84f3440c90e2742bf99400caa779e4f/Tekla.Extension/Enums/ProfileType.cs#L75-L79

2023-08-02 16:47 UTC, Blogbotana approved these changes
Super, perfect

2023-08-02 16:47 UTC, merged